collections_config:
  blog:
    path: blog
    name: Posts
    output: true
    icon: people
    add_options:
      - name: Add Post
        href: "cloudcannon::editor/:collections_dir/:base_path/.:extensionðŸ†•"
      - name: Add Draft
        href: "cloudcannon::editor/:collections_dir/:base_path_draftify/.:extensionðŸ†•:base_path_postify/_defaults.:extension"
  portfolio:
    path: portfolio
    output: true
    add_options:
      - name: Live Preview
        href: "[path]"
